                        <div class="shopp_ass_advright">
                            <figure>
                                <a href="//alothietkeweb.com.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qcr1.jpg"); ?>" /></a>
                            </figure>
                            <figure>
                                <a href="//download.com.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qcr2.jpg"); ?>" /></a>
                            </figure>
                            <figure>
                                <a href="//lagavi.com" target="_blank"><img src="<?php echo $this->basepath("public/img/qcr3.jpg"); ?>" /></a>
                            </figure>                                 
                            <div class="clear"></div>
                        </div> 