              <div class="shopp_ass">
              <div class="row">
                <div class="large-12 columns">
                    <!-- Place this tag where you want the +1 button to render. -->
                    <div class="g-plusone" data-annotation="bubble" data-width="300" data-href="<?php echo $this->serverurl(); ?>"></div>
                    
                        <!-- Place this tag after the last +1 button tag. -->
                        <script type="text/javascript">
                          (function() {
                            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                            po.src = 'https://apis.google.com/js/platform.js';
                            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                          })();
                        </script>
                        
                     <a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $this->serverurl(); ?>">Tweet</a>
                </div>
             </div>
             <div class="row">
                <div class="large-12 columns">
                    <script>
                        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)
                    	?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';
                    	fjs.parentNode.insertBefore(js,fjs);}}
                        (document, 'script', 'twitter-wjs');
                    </script>
                    
                    <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FCongDongTuoiTreVietNam&amp;width=2&amp;height=400&amp;colorscheme=dark&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false"
                        scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:270px; height:400px;" allowTransparency="true"></iframe>
                </div>
             </div>
            </div>