               <div class="banner-ads">
                    <figure>
                       <a href="//truyentranhonline.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qc1.gif"); ?>" /></a>
                        <a href="//kleverfruits.com.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qc2.jpg"); ?>" /></a>
                    </figure>
               </div>