        <div class="view-adv row">
            <figure class="large-12 small-11 small-centered columns">
                 <a href="//alothietkeweb.com.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qc1.gif"); ?>" /></a>
            </figure>
            <figure class="large-12 small-11 small-centered columns">
                 <a href="//alothietkeweb.com.vn" target="_blank"><img src="<?php echo $this->basepath("public/img/qc2.jpg"); ?>" /></a>
            </figure>
            </div>