<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Website Dang Xay Dung</title>
    <style type="text/css">
    body{margin:0; padding:0;}
    .container {
	    width: 900px;  
	    margin: 0 auto; 
	    margin-top: 0px;
    } 
 
    #main1 {
	    background-color: rgba(146,184,21,0.2);
	    padding: 10px;
	    border:3px solid rgba(146,184,21,0.4);
	    overflow:auto;
	    -webkit-border-radius: 3px;
	    -moz-border-radius: 3px;
	    border-radius: 3px;
	    height:500px;
    }
    </style>
</head>

<body>
<div class="container">
    <div id="main">
        <table style="" align="center">
            <tbody>
                <tr><td align="center"><img src="img/website-under-construction.gif" border="0"></td></tr>
            </tbody>
        </table>
	</div>
</div>

</body></html>