    	<h2 class="pl"><?php echo $this->escapehtml($TenTL->Tenloai)?></h2>
        	<section class="large-8 columns">
        	<?php if(count($DS_truyen) > 0): ?>
              <table>
                <thead>
                    <tr>
                      <th>Tên truyện</th>
                      <th>Tên chapter</th>
                      <th>Ngày đăng</th>
                      <th>Tình trạng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($DS_truyen as $lists): ?>
                             <tr>
                              <td><a class="name_mg" href="<?php echo $this->url('thongtintruyen', array('action' => 'index', 'id' => $lists->Matruyen, 'Tentruyen' => $lists->Tentruyenkhongdau)); ?>"><?php echo $this->escapehtml($lists->Tentruyen); ?></a></td>
                              <td><a href="<?php echo $this->url('viewtruyen', array('action' => 'index', 'id' => $lists->Machapter, 'Tenchapter' => $lists->Tenchapterkhongdau)); ?>"><?php echo $this->escapehtml($lists->Tenchapter); ?></a></td>
                              <td><?php echo $this->escapehtml(date_format(date_create($lists->Ngaydang), 'd-m-Y')); ?></td>
                              <td><?php echo $this->escapehtml($lists->Tinhtrang); ?></td>
                            </tr>
                <?php endforeach; ?>
                </tbody>            
              </table>
              <?php echo $this->paginationcontrol($DS_truyen, 'sliding', 'Partial/paginator.phtml', array('route' => 'theloai/paginator'));?>                                                                               
            <?php else: ?>
                <div class="shopp_ass"><p><h4>Không tìm thấy kết quả</h4></p></div>
                <?php endif; ?>
            </section>
 <aside class="large-4 columns">
        <?php echo $this->partial('Partial/DSTL_Partial.phtml'); ?>
        <?php echo $this->partial('Partial/advsright.phtml', null); ?>
</aside>