<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Truyencuoi\Module'                        => __DIR__ . '/Module.php',
    'Truyencuoi\Controller\IndexController' => __DIR__ . '/src/Truyencuoi/Controller/IndexController.php',
    'TruyencuoiTest\Framework\TestCase'        => __DIR__ . '/tests/Truyencuoi/Framework/TestCase.php',
    'TruyencuoiTest\SampleTest'                => __DIR__ . '/tests/Truyencuoi/SampleTest.php',
);
