<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Kiemhiep\Module'                        => __DIR__ . '/Module.php',
    'Kiemhiep\Controller\IndexController' => __DIR__ . '/src/Kiemhiep/Controller/IndexController.php',
    'KiemhiepTest\Framework\TestCase'        => __DIR__ . '/tests/Kiemhiep/Framework/TestCase.php',
    'KiemhiepTest\SampleTest'                => __DIR__ . '/tests/Kiemhiep/SampleTest.php',
);
