<h2 class="pl">Thông tin truyện</h2>
<section class="large-8 columns">
    <div class="shopp_ass">
       <div class="row">
            <figure class="large-4 medium-4 columns">
                <img class="th" src="<?php echo $this->escapehtml($TT_truyen->Hinhminhhoa) ?>" title="<?php echo $this->escapehtml($TT_truyen->Tentruyen) ?>" width="80" />
            </figure>
            <div class="large-8 medium-8 columns">
                <h3><?php echo $this->escapehtml($TT_truyen->Tentruyen) ?></h3>
                <p><span class="info">Tác giả: </span><a href="<?php echo $this->url('tacgia', array('action' => 'index', 'id' => $TT_truyen->Matacgia, 'Tentacgia' => $TT_truyen->Tentacgiakhongdau)); ?>"><?php echo $this->escapehtml($TT_truyen->Tentacgia) ?></a></p>
                <p><span class="info">Nhóm dịch: </span><a href="<?php echo $this->url('nhomdich', array('action' => 'index', 'id' => $TT_truyen->Nhomdichkhongdauslug))?>"><?php echo $this->escapehtml($TT_truyen->Nhomdich) ?></a></p>
                <p><span class="info">Thể loại: </span>
                <?php foreach ($TL_truyen as $TL):?>
                    <a href="<?php echo $this->url('theloai', array('action' => 'index', 'id' => $TL->Maloai, 'Tenloai' => $TL->Loaitruyenkhongdau)); ?>"><?php echo $this->escapehtml($TL->Tenloai) ?></a>&nbsp;&nbsp;
                <?php endforeach;?>
                <p><span class="info">Nhà xuất bản: </span><?php echo $this->escapehtml($TT_truyen->NhaXB) ?></p>
                <p><span class="info">Tình trạng: </span><?php echo $this->escapehtml($TT_truyen->Tinhtrang) ?></p>
                <p><span class="info">Nội dung: </span><?php echo $TT_truyen->Cottruyen ?></p>
            </div>
       </div>
                <fb:like href="<?php echo $this->serverurl($this->url('thongtintruyen', array('action' => 'index', 'id' => $TT_truyen->Matruyen, 'Tentruyen' => $TT_truyen->Tentruyenkhongdau))); ?>" width="auto" style="float:left; margin-right: 10px;" layout="button_count" action="like" show_faces="true" share="true"></fb:like>                                                                            
                <!-- Place this tag where you want the share button to render. -->
                <div class="g-plus" data-action="share" data-annotation="bubble" data-href="<?php echo $this->serverurl($this->url('thongtintruyen', array('action' => 'index', 'id' => $TT_truyen->Matruyen, 'Tentruyen' => $TT_truyen->Tentruyenkhongdau))); ?>"></div>
                <!-- Place this tag after the last share tag. -->
                <script type="text/javascript">
                  (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/platform.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                  })();
                </script>
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $this->serverurl($this->url('thongtintruyen', array('action' => 'index', 'id' => $TT_truyen->Matruyen, 'Tentruyen' => $TT_truyen->Tentruyenkhongdau))); ?>">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>       
    </div>
    <h2 class="pl">Danh sách chapter</h2>
              <table>
                <thead>
                    <tr>
                      <th>Tên chap</th>
                      <th>Ngày đăng</th>
                      <th>Lượt xem</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($Chap_TT as $Chapter): ?>
                        <tr>
                          <td><a href="<?php echo $this->url('viewtruyen', array('action' => 'index', 'id' => $Chapter->Machapter, 'Tenchapter' => $Chapter->Tenchapterkhongdau)); ?>"><?php echo $this->escapehtml($Chapter->Tenchapter); ?></a></td>
                          <td><?php echo $this->escapehtml(date_format(date_create($Chapter->Ngaydang), 'd-m-Y')); ?></td>
                          <td><?php echo rand(1000, 13121)?></td>
                        </tr>    
                <?php endforeach; ?>
                </tbody>
              </table>
              <script>
                  $(window).load(function(e){
                      (function(window){
                          var dh = null;
                          $(window).on("resize",function(){
                              if ( dh ) {
                                  clearTimeout(dh);
                              }
                              dh = setTimeout(function(){
                                  var $fbc = $(".fb-comments");
                                  var $stc = $(".comments-container");
                                  dh = null;
                                  if ( $fbc.attr("data-width") != $stc.width() ) {
                                      $stc.css({height:$stc.height()});
                                      $fbc.attr("data-width", $stc.width());
                                      FB.XFBML.parse($stc[0],function(){
                                          $stc.css({height:'auto'});
                                      });
                                  }
                              }, 300);
                          }).trigger("resize");
                      })(this);
                    });
              </script>
              <div class="comments-container">
                  <fb:comments class="fb-comments" href="<?php echo $this->serverurl($this->url('thongtintruyen', array('action' => 'index', 'id' => $TT_truyen->Matruyen, 'Tentruyen' => $TT_truyen->Tentruyenkhongdau))); ?>" numposts="10" colorscheme="dark"></fb:comments>
              </div>
              <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=564010057045875";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>      
</section>
<aside class="large-4 columns">
    <?php echo $this->partial('Partial/DSTL_Partial.phtml'); ?>
    <?php echo $this->partial('Partial/Truyencungtheloai.phtml', array('listtruyenTL' => $Listcungtltruyen)); ?>
    <?php echo $this->partial('Partial/advsright.phtml', null); ?>
</aside>