<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ngontinh\Module'                        => __DIR__ . '/Module.php',
    'Ngontinh\Controller\IndexController' => __DIR__ . '/src/Ngontinh/Controller/IndexController.php',
    'NgontinhTest\Framework\TestCase'        => __DIR__ . '/tests/Ngontinh/Framework/TestCase.php',
    'NgontinhTest\SampleTest'                => __DIR__ . '/tests/Ngontinh/SampleTest.php',
);
