<?php 
if (defined('RUNNING_FROM_ROOT')) {
  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php echo $this->headTitle()?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/ad-img/favicon.png'))
                        ->appendStylesheet($this->basePath() . '/ad-css/application.min.css'); ?>
                        
        <?php echo $this->headScript()->prependFile($this->basePath('ad-lib/jquery/jquery.1.9.0.min.js'))
                                      ->prependFile($this->basePath('ad-lib/backbone/underscore-min.js'))
                                      ->prependFile($this->basePath('ad-js/settings.js')); ?>
    </head>
<body>
<div class="single-widget-container">
    <section class="widget login-widget">
        <header class="text-align-center">
            <h4>Login to your account</h4>
        </header>
        <div class="body">
            <form class="no-margin" action="<?php echo $this->url("auth", array('action' => 'authenticate')); ?>" method="post" >
                <fieldset>
                    <div class="control-group no-margin">
                        <label class="control-label" for="username">Username</label>
                        <div class="control">
                            <div class="input-prepend input-padding-increased">
                                <span class="add-on">
                                    <i class="eicon-user icon-large"></i>
                                </span>
                                <input name="uname" type="text" placeholder="Your username" />
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="password">Password</label>
                        <div class="control">
                            <div class="input-prepend input-padding-increased">
                                <span class="add-on">
                                    <i class="icon-lock icon-large"></i>
                                </span>
                                <input name="pass" type="password" placeholder="Your Password" />
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-actions">
                    <button type="submit" class="btn btn-block btn-large btn-danger">
                        <span class="small-circle"><i class="icon-caret-right"></i></span>
                        <small>Sign In</small>
                    </button>
                    <div class="forgot"><a class="forgot" href="#">Forgot Username or Password?</a></div>
                </div>
            </form>
        </div>
        <footer>
            <div class="facebook-login">
                <a href="<?php echo $this->url('admin'); ?>"><span><i class="icon-facebook-sign icon-large"></i> LogIn with Facebook</span></a>
            </div>
        </footer>
    </section>
</div>
</body>
</html>